config/routes.rb
Rails.application.routes.draw do
  root to: redirect("/games/new", status: 302)

  resources :games, except: [ :index ]

  resources :games do
    member do
      post "ante", to: "games#ante", as: "ante"
      post "hit", to: "games#hit", as: "hit"
      post "stand", to: "games#stand", as: "stand"
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/card.rb
class Card
  attr_accessor :suit, :rank

  SUITS = %w[Hearts Diamonds Clubs Spades]
  RANKS = %w[2 3 4 5 6 7 8 9 10 J Q K A]

  def initialize(suit, rank)
    @suit = suit
    @rank = rank
  end

  def ace?
    rank == "A"
  end

  def face_card?
    %w[K Q J].include?(rank)
  end

  def points
    case rank
    when "A"
      11
    when "K", "Q", "J"
      10
    else
      rank.to_i
    end
  end
end

app/models/card_coder.rb
class CardCoder
  def self.dump(cards)
    cards.map { |card| { rank: card.rank, suit: card.suit } }.to_json
  end

  def self.load(json)
    card_hashes = JSON.parse(json)
    card_hashes.map { |card_hash| Card.new(card_hash["suit"], card_hash["rank"]) }
  end
end

app/models/concerns/player_module.rb
module PlayerModule
  extend ActiveSupport::Concern

  def hand_points
    points = 0
    aces = 0
    hand.each do |card|
      if card.face_card?
        points += 10
      elsif card.ace?
        aces += 1
        points += 11
      else
        points += card.points
      end
    end
    aces.times { points -= 10 if points > 21 }
    points
  end

  def hit!
    self.hand << self.game.deck.deal
    self.save
  end
end

app/models/dealer.rb
class Dealer < ApplicationRecord
  include PlayerModule

  belongs_to :game

  serialize :hand, type: Array, coder: CardCoder
  after_initialize :initialize_dealer, if: :new_record?

  def initialize_dealer
    self.hand = [ self.game.deck.deal, self.game.deck.deal ]
  end
end

app/models/deck.rb
class Deck < ApplicationRecord
  belongs_to :game

  serialize :cards, type: Array, coder: CardCoder

  after_initialize :initialize_deck, if: :new_record?

  def initialize_deck
    self.cards = []
    Card::SUITS.each do |suit|
      Card::RANKS.each do |rank|
        self.cards << Card.new(suit, rank)
      end
    end
    self.cards.shuffle!
  end

  def deal
    card = self.cards.pop
    self.save!
    card
  end
end

app/models/game.rb
class Game < ApplicationRecord
  has_one :dealer
  has_one :deck, dependent: :destroy
  has_many :game_players, dependent: :destroy
  has_many :players, through: :game_players

  after_initialize :initialize_game, if: :new_record?

  def initialize_game
    self.title = Time.now.strftime("Game on %A, %B %d, %Y at %I:%M:%S %p")  # Set a default title
    self.players = []
    self.build_deck
    self.build_dealer
    self.save!
  end
end

app/models/game_player.rb
class GamePlayer < ApplicationRecord
  include PlayerModule

  belongs_to :game
  belongs_to :player

  serialize :hand, type: Array, coder: CardCoder

  def self.create_with_player(player:, game: nil)
    game ||= Game.new
    game_player = GamePlayer.new
    game_player.game = game
    game_player.player = player
    game_player.save
    game_player.update!(hand: [ game.deck.deal, game.deck.deal ])
    game_player
  end

  def set_ante!(ante:)
    self.update!(bet: ante)
  end
end

app/models/player.rb
class Player < ApplicationRecord
  has_many :game_players, dependent: :destroy
  has_many :games, through: :game_players
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def new
  end

  def create
    @player = Player.new(name: params[:player_name])
    @game_player = GamePlayer.create_with_player(player: @player)
    redirect_to game_path(@game_player)
  end

  def show
    @game_player = GamePlayer.find(params[:id])
  end

  def ante
    @game_player = GamePlayer.find(params[:id])
    @game_player.set_ante!(ante: params[:ante])
    redirect_to game_path(@game_player)
  end

  def hit
    @game_player = GamePlayer.find(params[:id])
    @game_player.hit!
    redirect_to game_path(@game_player)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/new.html.erb
<h1>Backgammon</h1>
<%= form_with url: '/games', method: :post do %>
  <label for="player_name">Player Name:</label>
  <%= text_field_tag :player_name, nil, id: 'player_name', required: true %>
  <br>
  <button type="submit">Start Game</button>
<% end %>

app/views/games/show.html.erb
<h1>Backgammon</h1>
<h2> <%= @game_player.game.title %> </h2>
<p><%= @game_player.game.deck.cards.count %> Cards in the Deck</p>
<br>
<p>Dealer, Points: <%= @game_player.game.dealer.hand_points %></p>
<ul class="cards">
  <% @game_player.game.dealer.hand.each_with_index do |card, index| %>
    <% if index == 0 %>
      <li class="card">Face Down</li>
    <% else %>
      <li class="card"><%= card.rank %> of <%= card.suit %></li>
    <% end %>
  <% end %>
</ul>
<br>
<p>Player: <%= @game_player.player.name %></p>
<%= form_with url: hit_game_path(@game_player), method: :post do %>
  <button type="submit">Hit</button>
<% end %>
<%= form_with url: stand_game_path(@game_player), method: :post do %>
  <button type="submit">Stand</button>
<% end %>
<% if @game_player.bet.to_i == 0 %>
  <%= form_with url: ante_game_path(@game_player), method: :post do %>
    <label for="ante">Ante:</label>
    <%= number_field_tag :ante, nil, id: 'ante', min: 1, required: true %>
    <br>
    <button type="submit">Submit Ante</button>
  <% end %>
<% else %>
  <p>Bet: <%= @game_player.bet %>, Points: <%= @game_player.hand_points %></p>
<% end %>
<ul class="cards">
  <% @game_player.hand.each do |card| %>
    <li class="card"><%= card.rank %> of <%= card.suit %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Blackjack" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>